version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: escra-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escra_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: escra-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    container_name: escra-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/escra_db
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DB_NAME: escra_db
      PORT: "8000"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./escra-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://192.168.222.44:8000
    container_name: escra-frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  mongodb_data:
