version: '3.8'

services:
  escra-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    image: escra-frontend:latest
    container_name: escra-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {if (r.statusCode !== 200) throw new Error()})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development configuration
  escra-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: escra-frontend:dev
    container_name: escra-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev